# Generated by Django 5.2.14 on 2026-05-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_a', models.FloatField()),
                ('temperature_c', models.FloatField()),
                ('humidity_pct', models.FloatField()),
                ('alert', models.BooleanField(default=False)),
                ('critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
