# Generated by Django 5.2.14 on 2026-05-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='peak_current_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='power_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='rms_current_a',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
